# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGl3keFLlYPygFu1HyBJ2CXhjQM_IBq_

Streamlit UI (app.py)
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import logging
from src.data_processor import DataProcessor
from src.code_generator import CodeGenerator
from src.report_generator import ReportGenerator
from src.config import APP_TITLE, MAX_FILE_SIZE_MB, LLM_MODEL

# 設定logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# --- 1. 初始化 Session State (小口袋) ---
# 確保即使按下「執行按鈕」導致整頁刷新，這些內容也不會弄丟
if "generated_code" not in st.session_state:
    st.session_state.generated_code = ""
if "insights" not in st.session_state:
    st.session_state.insights = ""
if "df" not in st.session_state:
    st.session_state.df = None

# Streamlit頁面設定
st.set_page_config(page_title=APP_TITLE, layout="wide")
st.title("🔧 Manufacturing AI Code & Report Assistant")
st.markdown("用自然語言生成製造業資料分析代碼與報告")

# Sidebar 參數
with st.sidebar:
    st.header("⚙️ 設定")
    model_choice = st.selectbox(
        "選擇LLM模型",
        ["qwen2.5:0.5b", "local-ollama", "gpt-3.5-turbo"],
        help="建議 MX110 顯卡使用 1.5b 模型以避免崩潰"
    )
    temperature = st.slider("Temperature (創意度)", 0.0, 1.0, 0.7)
    st.markdown("---")
    st.info("💡 步驟：上傳檔案 → 生成代碼 → 點擊執行代碼")

# 主程式區
st.markdown("## 步驟1: 上傳資料")
uploaded_file = st.file_uploader(
    "上傳CSV或Excel檔案",
    type=["csv", "xlsx"],
    help=f"檔案大小限制: {MAX_FILE_SIZE_MB}MB"
)

if uploaded_file:
    # 讀取並保存資料到 session_state
    if st.session_state.df is None:
        processor = DataProcessor()
        st.session_state.df = processor.load_file(uploaded_file)
        st.success(f"✅ 已讀取 {len(st.session_state.df)} 行")

    df = st.session_state.df
    st.dataframe(df.head(10))

    st.markdown("## 步驟2: 輸入分析需求")
    user_request = st.text_area(
        "描述你要分析的內容",
        value="分析本週良率趨勢並找出Top3異常因子",
        height=80
    )

    st.markdown("## 步驟3: AI生成代碼")
    # 生成按鈕：只負責「產生」內容並放入「口袋」
    if st.button("🚀 生成代碼 & 報告", type="primary"):
        with st.spinner("AI 思考中 (這可能需要一點時間)..."):
            processor = DataProcessor()
            processor.df = df # 同步資料
            data_summary = processor.get_summary()
            schema = {col: str(df[col].dtype) for col in df.columns}

            # 模型名稱判斷邏輯
            final_model = LLM_MODEL if model_choice == "local-ollama" else model_choice
            
            generator = CodeGenerator(model_name=final_model)
            result = generator.generate_code(
                user_request=user_request,
                data_summary=data_summary,
                sample_dataframe_schema=schema
            )
            
            # 將結果存入「口袋」
            st.session_state.generated_code = result['code']
            st.session_state.insights = result['insights']

    # --- 關鍵區域：顯示與執行 ---
    # 只要「口袋」裡有東西，就顯示出來
    if st.session_state.generated_code:
        st.subheader("📝 生成的Python代碼")
        
        # 讓使用者可以微調代碼，修改會即時同步回口袋
        st.session_state.generated_code = st.text_area(
            "編輯代碼區：",
            value=st.session_state.generated_code,
            height=250
        )

        # 點擊此按鈕會觸發整頁重新執行，但因為我們用了 session_state，代碼不會消失
        if st.button("▶️ 執行代碼"):
            st.markdown("### 📊 執行結果")
            try:
                exec_globals = {
                    'df': df, 'pd': pd, 'np': np, 'plt': plt, 'st': st,
                    '__builtins__': __builtins__,  # ← 加這行
                }
                exec_locals = {}  # ← 加這行
                exec(st.session_state.generated_code, exec_globals, exec_locals)  # ← 改這行
                st.success("✅ 代碼執行成功")
            except Exception as e:
                st.error(f"❌ 執行出錯: {e}")

        # 顯示洞察與報告下載 (從口袋拿)
        st.subheader("💡 AI洞察")
        st.markdown(st.session_state.insights)

        st.subheader("📊 完整報告下載")
        report_gen = ReportGenerator(title="Manufacturing Analysis Report")
        report_gen.add_section("分析需求", user_request)
        report_gen.add_section("生成代碼", st.session_state.generated_code, section_type="code")
        report_gen.add_section("主要發現", st.session_state.insights, section_type="insight")

        c1, c2 = st.columns(2)
        with c1:
            st.download_button("📥 下載Markdown", data=report_gen.generate_markdown(), file_name="report.md")
        with c2:
            st.download_button("📥 下載HTML", data=report_gen.generate_html(), file_name="report.html")

else:
    # 如果清空檔案，也要清空口袋
    st.session_state.generated_code = ""
    st.session_state.df = None
    st.info("👈 請先上傳CSV或Excel檔案")