# -*- coding: utf-8 -*-
"""report_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eGl3keFLlYPygFu1HyBJ2CXhjQM_IBq_

report_generator.py - 報告生成
"""

import logging
from datetime import datetime
from typing import Dict, Optional
import markdown
from pathlib import Path

logger = logging.getLogger(__name__)

class ReportGenerator:
    """
    生成Markdown/HTML報告，整合數據、代碼、insights。
    """

    def __init__(self, title: str = "Manufacturing Analysis Report"):
        self.title = title
        self.sections = []

    def add_section(self,
                    heading: str,
                    content: str,
                    section_type: str = "text") -> None:
        """
        新增報告段落。

        Args:
            heading: 段落標題
            content: 內容 (markdown或plain text)
            section_type: 'text', 'code', 'table', 'insight'
        """

        self.sections.append({
            'heading': heading,
            'content': content,
            'type': section_type,
        })

    def add_insight(self, insight: str) -> None:
        """新增洞察 (highlighted)"""

        formatted = f"💡 **Insight**: {insight}"
        self.add_section("Key Finding", formatted, "insight")

    def generate_markdown(self) -> str:
        """生成完整Markdown報告"""

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        md = f"""# {self.title}

**Generated**: {timestamp}

***

"""

        for section in self.sections:
            heading = section['heading']
            content = section['content']
            section_type = section['type']

            md += f"## {heading}\n\n"

            if section_type == 'code':
                md += f"```python\n{content}\n```"
            elif section_type == 'insight':
                md += f"{content}\n\n"
            else:
                md += f"{content}\n\n"

            md += "---\n\n"

        return md

    def generate_html(self) -> str:
        """轉換為HTML"""

        md_content = self.generate_markdown()
        html = markdown.markdown(md_content, extensions=['extra', 'codehilite'])

        # 包裝成完整HTML
        full_html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{self.title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; }}
        h1 {{ color: #333; }}
        h2 {{ color: #666; margin-top: 30px; }}
        pre {{ background: #f4f4f4; padding: 10px; border-radius: 5px; }}
        code {{ background: #f4f4f4; padding: 2px 5px; }}
    </style>
</head>
<body>
    {html}
</body>
</html>
"""
        return full_html

    def save_to_file(self, file_path: str, format: str = "md") -> None:
        """
        保存報告到文件。

        Args:
            file_path: 輸出路徑
            format: 'md' 或 'html'
        """

        content = self.generate_markdown() if format == "md" else self.generate_html()

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        logger.info(f"Report saved to {file_path}")